# hostname_config.cmake

execute_process(COMMAND hostname OUTPUT_VARIABLE HOSTNAME OUTPUT_STRIP_TRAILING_WHITESPACE)
message(STATUS "Current machine hostname: ${HOSTNAME}")

if (${HOSTNAME} STREQUAL "redamancyguy-UBUNTU")
    set(CMAKE_CXX_STANDARD 23)
    set(CMAKE_C_STANDARD 17)
    set(CMAKE_CUDA_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_C_STANDARD_REQUIRED ON)
    add_definitions(-DUBUNTU_DESKTOP)
    set(Torch_DIR "/home/redamancyguy/Desktop/libtorch/share/cmake/Torch")
    set(CMAKE_CUDA_COMPILER /usr/local/cuda/bin/nvcc)
    find_package(Torch REQUIRED)
    find_package(Boost REQUIRED COMPONENTS fiber date_time system filesystem)
    find_package(Python REQUIRED COMPONENTS Interpreter Development)
elseif(${HOSTNAME} STREQUAL "redamancyguy")
    set(CMAKE_CXX_STANDARD 23)
    set(CMAKE_C_STANDARD 17)
    set(CMAKE_CUDA_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_C_STANDARD_REQUIRED ON)
    add_definitions(-DUBUNTU_DESKTOP_WSL)
    set(Torch_DIR "/mnt/d/ENV/libtorch/share/cmake/Torch")
    set(CMAKE_CUDA_COMPILER /usr/local/cuda/bin/nvcc)
    find_package(Torch REQUIRED)
    find_package(Boost REQUIRED COMPONENTS fiber date_time system filesystem)
    find_package(Python REQUIRED COMPONENTS Interpreter Development)
elseif(${HOSTNAME} STREQUAL "DESKTOP-NTTJGLQ")
    set(CMAKE_CXX_STANDARD 23)
    set(CMAKE_C_STANDARD 17)
    set(CMAKE_CUDA_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_C_STANDARD_REQUIRED ON)
    add_definitions(-DUBUNTU_NOTEBOOK)
    set(Torch_DIR "/mnt/c/Users/redamancyguy/Desktop/libtorch/share/cmake/Torch")
    set(CMAKE_CUDA_COMPILER /usr/local/cuda/bin/nvcc)
    find_package(Torch REQUIRED)
    find_package(Boost REQUIRED COMPONENTS fiber date_time system filesystem)
elseif(${HOSTNAME} STREQUAL "redamancyguy-Precision-7920-Tower")
    set(CMAKE_CXX_STANDARD 23)
    set(CMAKE_C_STANDARD 17)
    set(CMAKE_CUDA_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_C_STANDARD_REQUIRED ON)
    add_definitions(-DUBUNTU_CPU_SERVER)
    set(Torch_DIR "/home/redamancyguy/libtorch/libtorch/share/cmake/Torch")
    set(CMAKE_CUDA_COMPILER /usr/local/cuda/bin/nvcc)
    find_package(Torch REQUIRED)
    find_package(Boost REQUIRED COMPONENTS fiber date_time system filesystem)
else ()
    message(FATAL_ERROR "unknown machine.")
endif()
